### ISSUE TITLE
Not able to run the repo.

### ISSUE THREAD

**Issue by yaswanthkata** [dayanrr91/aws-net-core-examples#1]
Hi ,

I have followed all the steps mentioned in the readme.txt
But iam getting error when running .
![image](https://user-images.githubusercontent.com/3971157/52357366-0faf1100-2a5c-11e9-84a4-1c6f7367c694.png)

my credentials file has region=[ap-south-1] specified.

Please help me in fixing this ,Thanks

**Comment by dayanrr91** [comment]
Hi, are you sure you created the document named **.aws** with the right structure?, because that error is caused because your api it is not founding the credentials.

Also you need to check the name of your region here:
https://docs.aws.amazon.com/general/latest/gr/rande.html
